apiVersion: v1
data:
  proxysql.cnf: |2-

    datadir="/var/lib/proxysql"
    admin_variables=
    {
      admin_credentials="proxysql-admin:adminpassw0rd"
      mysql_ifaces="0.0.0.0:6032"
      refresh_interval=2000
    }
    mysql_variables=
    {
      threads=4
      max_connections=2048
      default_query_delay=0
      default_query_timeout=36000000
      have_compress=true
      poll_timeout=2000
      interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
      default_schema="information_schema"
      stacksize=1048576
      server_version="5.1.30"
      connect_timeout_server=10000
      monitor_history=60000
      monitor_connect_interval=200000
      monitor_ping_interval=200000
      ping_interval_server_msec=10000
      ping_timeout_server=200
      commands_stats=true
      sessions_sort=true
      monitor_username="proxysql"
      monitor_password="proxysqlpassw0rd"
      ssl_p2s_cert=""
      ssl_p2s_key=""
      ssl_p2s_ca=""
    }
    mysql_servers=
    (
      { address="{{ .Values.sql_writer }}" , port=3306 , hostgroup=5, max_connections=1000, use_ssl=0 },
      { address="{{ .Values.sql_reader_one }}" , port=3306 , hostgroup=10, max_connections=1000, use_ssl=0 },
      { address="{{ .Values.sql_reader_two }}" , port=3306 , hostgroup=10, max_connections=1000, use_ssl=0 }
    )
    mysql_users=
    (
      { username = "{{ .Values.sql_username }}" , password = "{{ .Values.sql_password }}" , default_hostgroup = 5 , active = 1 }
    )
    mysql_query_rules=
    (
      { rule_id = "1" , username="{{ .Values.sql_username }}" , active=1 , match_digest="^SELECT .* FOR UPDATE" , destination_hostgroup=5 , apply=1, comment="select for update goes to the writer: chester-test" },
      { rule_id = "2" , username="{{ .Values.sql_username }}" , active=1 , match_digest="^SELECT" , destination_hostgroup=10 , apply=1, comment="selects go to the reader: chester-test" },
      { rule_id = "3" , username="{{ .Values.sql_username }}" , active=1 , match_digest=".*" , destination_hostgroup=5 , apply=1, comment="catch all to writer: chester-test" },
      { rule_id = "4" , username="{{ .Values.sql_username }}" , active=1 , match_digest="^DELETE" , destination_hostgroup=5 , apply=1, comment="deletes to writer: chester-test" }
    )
kind: ConfigMap
metadata:
  labels:
    instancegroup: chester-test
  name: proxysql-configmap-proxysql-chester
  namespace: proxysql
