apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "proxysql.fullname" . }}-hpa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "proxysql.name" . }}
    chart: {{ template "proxysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment }}
    team: {{ .Values.team }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "proxysql.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.targetCPUUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.targetMemoryUtilization }}