---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | lower }}
  labels:
    app: {{ template "proxysql.name" . }}
    chart: {{ template "proxysql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.proxysqlmysqlport }}
      name: proxysql-mysql
    - port: {{ .Values.service.proxysqladminport }}
      name: proxysql-admin
  selector:
    app: {{ template "proxysql.name" . }}
    release: {{ .Release.Name }}
