apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "chester-api.fullname" . }}
  labels:
    app: {{ template "chester-api.name" . }}
    chart: {{ template "chester-api.chart" . }}
    release: {{ .Release.Name }}
    environment: {{ .Values.environment }}
    team: {{ .Values.team }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chester-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chester-api.name" . }}
        release: {{ .Release.Name }}
        environment: {{ .Values.c_env.env }}
    spec:
      volumes:
        - name: service-account
          secret:
            secretName: {{ .Values.secret.name }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: service-account
              mountPath: /etc/serviceAccount
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: {{ .Values.service.healthCheck }}
              port: {{ .Values.service.targetPort }}
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 60
            httpGet:
              path: {{ .Values.service.healthCheck }}
              port: {{ .Values.service.targetPort }}
          env:
          {{- range $key, $value := .Values.c_env }}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
