apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: "{\"ports\": {\" {{ .Values.service.name }}\":\"{{ template "chester-api.fullname" . }}-backendconfig\"}}"
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "chester-api.name" . }}
    chart: {{ template "chester-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if not .Values.service.omitClusterIP }}
  {{ with .Values.service.clusterIP }}clusterIP: {{ quote . }}{{ end }}
{{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "chester-api.name" . }}
    release: {{ .Release.Name }}